---
title: "Assignment 4"
author: "Dani Antos"
date: "7/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Assignment 4

```{r making GLM}
setwd("C:/Users/dania/Documents/Pitt/BioStats/Module 4")
x <- read.table("op.txt",sep="\t",header=T,stringsAsFactors=F)
x$SITE.CODED <- factor(x$SITE.CODED)
x 
OP <- c(0,	1,	0,	0,	0,	0,	0,	1,	0,	1,	1,	1,	0,	0,	1,	1,	1,	0,	0,	0,	0,	1,	0,	1,	1,	0,	1,	0,	0,	1,	0,	0,	1,	0,	0,	1,	0,	0,	0,	1,	0,	1,	1,	0,	0,	1,	0,	0,	0,	1,	1,	1,	0,	0,	0,	0,	1,	0,	1,	1,	0,	1,	0,	0,	0,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	0,	0,	0,	1,	1,	0,	1,	0,	1,	1,	1,	0,	1,	0,	0,	0,	1,	0,	0,	0,	0,	1,	1,	1,	1,	0,	0,	1,	0,	0,	0,	1,	1,	0,	1,	0,	1,	0,	0,	0,	1,	0,	1,	0,	1,	1,	1,	1,	1,	1,	1,	1,	1,	0,	1,	1,	1,	1,	1,	1,	1,	1,	1,	1,	0,	1,	0,	1,	1,	1,	1,	1,	0,	1,	0,	0,	1,	1,	0,	1,	1,	1,	1,	0,	1,	1,	1,	1,	1,	1,	0,	1,	1,	1,	0,	0,	1,	0,	0,	0,	0,	0,	1,	0,	0,	1,	1,	1,	0,	1,	0,	0,	0,	0,	1,	1,	0,	1,	0,	1,	0,	1,	0,	0,	0,	1,	0,	0,	0,	1,	0,	0,	0,	0,	0,	0,	0,	1,	1,	1,	0,	0,	0,	0,	1,	1,	0,	0,	0,	0,	0,	1,	0,	0,	1,	1,	0,	0,	0,	1,	1,	1,	1,	0,	0,	1,	1,	0,	0,	0,	0,	0,	0,	1,	0,	0, 1,	1,	0,	0,	0,	0,	1,	0,	1,	0,	0,	1,	0,	0,	0,	1,	0,	0,	0,	0,	1,	0,	0,	1,	1,	0,	0,	1,	1,	0,	0,	1,	0,	1,	0,	0,	1,	0,	0,	1,	0,	1,	1,	0,	0,	0,	0,	0,	0,	1,	1,	0,	1,	1,	0,	0,	0,	1,	0,	0,	0,	0,	1,	1,	1,	0,	1,	0,	1,	0,	0,	0,	0,	0,	0,	0,	0,	0,	1,	0,	1,	1,	1,	1,	0,	0,	0)
glm <- glm(OP~fev1.pct+fvc.pct+dlco.pct+PREOP.CA+PREOP.CAD+PREOP.COPD+PREOP.DM+PREOP.GERD+PREOP.HTN+T.SIZE+SITE.CODED, family="binomial",data=x)
summary(glm)
anova(glm, test="LR")
library(car)
Anova(glm,test="LR") #same four are significant, taking all but those four out of the model


glm2 <- glm(OP~fev1.pct+PREOP.COPD+T.SIZE+SITE.CODED,family="binomial",data=x)
anova(glm2,test="LR")
Anova(glm2,test="LR")

stripchart(predict(glm2,type="response")~OP,vertical=T, na.action = na.omit,pch=1,col="navy",
xlab="Operation Type",ylab="Estimated P(Operation Type)",
xaxt="n")
axis(1,at=1:2,c("Lobectomy","Segmentectomy"))
```

OP <- x$OP
predict <- predict(glm2,type="response")
stripchart(predict~OP,vertical=T, na.action = na.omit,pch=1,col="navy",
xlab="Died Within 1 Week",ylab="Estimated P(Died Within 1 Week)") #response will give on a probability logit scale
#I can get predicted values but for some reason can't get the plot, no idea what's happening


```{r ROC curve}
library(epiDisplay)
roc1 <- lroc(glm,graph=TRUE,line.col="red",grid=FALSE)
roc2 <- lroc(glm2,add=TRUE,line.col="navy",grid=FALSE)
```
```{r Plotting real data}
with(x,boxplot(fev1.pct~OP,xlab="Surgery",
	ylab="FEV",xaxt="n")) 
axis(1,at=1:2,labels=c("Lobectomy","Segmentectomy")) 
with(x,boxplot(PREOP.COPD~OP,xlab="Surgery",
	ylab="COPD History",xaxt="n"))
axis(1,at=1:2,labels=c("Lobectomy","Segmentectomy"))
with(x,boxplot(T.SIZE~OP,xlab="Surgery",
	ylab="Tumor Size",xaxt="n"))
axis(1,at=1:2,labels=c("Lobectomy","Segmentectomy"))
with(x,plot(SITE.CODED~OP,xlab="Surgery",
	ylab="Tumor Site"))

```

```{r Correlation}
cor.test(x$PREOP.COPD, x$fev1.pct)
cor.test(x$PREOP.COPD, x$T.SIZE)
library(polycor)
copd <- x$PREOP.COPD
site <- x$SITE.CODED
matrix <- x[,c(7,12)]
hetcor(matrix)
polyserial(x$PREOP.COPD,x$SITE.CODED)
cor(x$fev1.pct,x$T.SIZE)
polyserial(x$T.SIZE,x$SITE.CODED)
polyserial(x$fev1.pct,x$SITE.CODED)
```

```{r correlation for nonsignificant predictors}
cor(x$fev1.pct,x$fvc.pct)
cor(x$fev1.pct,x$dlco.pct)
cor.test(x$fev1.pct, x$PREOP.CA)
cor.test(x$fev1.pct, x$PREOP.CAD)
cor.test(x$fev1.pct, x$PREOP.DM)
cor.test(x$fev1.pct, x$PREOP.GERD)
cor.test(x$fev1.pct, x$PREOP.HTN)
cor(x$fvc.pct,x$dlco.pct)
cor.test(x$fvc.pct, x$PREOP.CA)
cor.test(x$fvc.pct, x$PREOP.CAD)
cor.test(x$fvc.pct, x$PREOP.COPD)
cor.test(x$fvc.pct, x$PREOP.DM)
cor.test(x$fvc.pct, x$PREOP.GERD)
cor.test(x$fvc.pct, x$PREOP.HTN)
cor(x$fvc.pct,x$T.SIZE)
polyserial(x$fvc.pct, x$SITE.CODED)
cor.test(x$dlco.pct, x$PREOP.CA)
cor.test(x$dlco.pct, x$PREOP.CAD)
cor.test(x$dlco.pct, x$PREOP.COPD)
cor.test(x$dlco.pct, x$PREOP.DM)
cor.test(x$dlco.pct, x$PREOP.GERD)
cor.test(x$dlco.pct, x$PREOP.HTN)
cor(x$dlco.pct, x$T.SIZE)
polyserial(x$dlco.pct, x$SITE.CODED)
cor(x$PREOP.CA, x$PREOP.CAD)
cor(x$PREOP.CA, x$PREOP.COPD)
cor(x$PREOP.CA, x$PREOP.DM)
cor(x$PREOP.CA, x$PREOP.GERD)
cor(x$PREOP.CA, x$PREOP.HTN)
cor.test(x$PREOP.CA, x$T.SIZE)
polyserial(x$PREOP.CA, x$SITE.CODED)
cor(x$PREOP.CAD, x$PREOP.COPD)
cor(x$PREOP.CAD, x$PREOP.DM)
cor(x$PREOP.CAD, x$PREOP.GERD)
cor(x$PREOP.CAD, x$PREOP.HTN)
cor.test(x$PREOP.CAD, x$T.SIZE)
polyserial(x$PREOP.CAD, x$SITE.CODED)
cor(x$PREOP.COPD, x$PREOP.DM)
cor(x$PREOP.COPD, x$PREOP.GERD)
cor(x$PREOP.COPD, x$PREOP.HTN)
cor(x$PREOP.DM, x$PREOP.GERD)
cor(x$PREOP.DM, x$PREOP.HTN)
cor.test(x$PREOP.DM, x$T.SIZE)
polyserial(x$PREOP.DM, x$SITE.CODED)
cor(x$PREOP.GERD, x$PREOP.HTN)
cor.test(x$PREOP.GERD, x$T.SIZE)
polyserial(x$PREOP.GERD, x$SITE.CODED)
cor.test(x$PREOP.HTN, x$T.SIZE)
polyserial(x$PREOP.HTN, x$SITE.CODED)
```

